//
//  SignupProtocols.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import Foundation

//MARK: - Wireframe
protocol SignupWireframeProtocol: class {
    func goBack()
}

//MARK: - Presenter
protocol SignupPresenterProtocol: class {
    func didTapLogin()
}

//MARK: - Interactor
protocol SignupInteractorProtocol: class {
    var presenter: SignupPresenterProtocol?  { get set }
}

//MARK: - View
protocol SignupViewProtocol: class {
    var presenter: SignupPresenterProtocol?  { get set }
    
    func showError(_ error: Error)
}
