//
//  SignupProtocols.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import RxRelay

//MARK: - Wireframe
protocol SignupWireframeProtocol: class {
    func goBack()
    func moveToTodoList()
}

//MARK: - Presenter
protocol SignupPresenterProtocol: class {
    var result: PublishRelay<Void> { get }
    var error: PublishRelay<Error> { get }
    
    func doSignup(username: String, password: String)
    
    func didTapLogin()
}

//MARK: - Interactor
protocol SignupInteractorProtocol: class {
    var presenter: SignupPresenterProtocol?  { get set }
    
    func requestSignup(username: String, password: String)
}

//MARK: - View
protocol SignupViewProtocol: class {
    var presenter: SignupPresenterProtocol?  { get set }
    
    func showError(_ error: Error)
}
