//
//  SignupPresenter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import UIKit

class SignupPresenter: SignupPresenterProtocol {
    weak private var view: SignupViewProtocol?
    var interactor: SignupInteractorProtocol?
    private let router: SignupWireframeProtocol?

    init(view: SignupViewProtocol, interactor: SignupInteractorProtocol?, router: SignupWireframeProtocol?) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func didTapLogin() {
        router?.goBack()
    }
}
