//
//  SignupInteractor.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import RxSwift

class SignupInteractor: SignupInteractorProtocol {
    weak var presenter: SignupPresenterProtocol?
    
    let disposeBag = DisposeBag()
    
    var authRequest = AuthRequest()
    
    func requestSignup(username: String, password: String) {
        let params = [
            "email": username,
            "password": password
        ]
        guard let presenter = presenter else { return }
        authRequest.signup(params)
            .compactMap {
                response in
                response.result
        }
        .map { $0.token }
        .do(onNext: saveToken(token:))
        .map { _ in () }
        .do(onError: presenter.error.accept)
        .catchError { _ in Observable.empty() }
        .subscribe()
            //            .bind(to: presenter.result)
            .disposed(by: disposeBag)
        //        request.subscribe(onError: presenter.error.accept).disposed(by: disposeBag)
    }
    
    func saveToken(token: String) {
        AppPreferences.instance.token = token
    }
}
