//
//  SignupRouter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import UIKit

class SignupRouter: SignupWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AppStoryboard.main.viewController(of: SignupViewController.self)
        let interactor = SignupInteractor()
        let router = SignupRouter()
        let presenter = SignupPresenter(view: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func moveToTodoList() {
            let vc = TodoListRouter.createModule()
            vc.modalPresentationStyle = .fullScreen
    //        if let navigationController = viewController?.navigationController {
    //            navigationController.pushViewController(vc, animated: true)
    //        } else {
                viewController?.present(vc, animated: true)
    //        }
        }
    
    func goBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
