//
//  LoginPresenter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import RxSwift
import RxRelay

class LoginPresenter: LoginPresenterProtocol {
    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol?
    
    lazy var disposeBag = DisposeBag()
    
    lazy var result = PublishRelay<Void>()
    lazy var error = PublishRelay<Error>()

    init(view: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol?) {
        self.view = view
        self.interactor = interactor
        self.router = router
        
        bindModel()
    }
    
    private func bindModel() {
        result.subscribe(onNext: {
            [weak self] _ in
            self?.router?.moveToTodoList()
        }).disposed(by: disposeBag)
        guard let view = view else { return }
        error.subscribe(onNext: view.showError).disposed(by: disposeBag)
    }

    func doLogin(username: String, password: String) {
        interactor?.requestLogin(username: username, password: password)
    }
    
    func didTapSignup() {
        router?.moveToSignup()
    }
}
