//
//  SuperSwitcherRouter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import UIKit

class SuperSwitcherRouter: SuperSwitcherWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AppStoryboard.main.viewController(of: SuperSwitcherViewController.self)
        let router = SuperSwitcherRouter()
        let presenter = SuperSwitcherPresenter(view: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func moveToTodoList() {
        let vc = TodoListRouter.createModule()
        vc.modalPresentationStyle = .fullScreen
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(vc, animated: true)
        } else {
            viewController?.present(vc, animated: true)
        }
    }
    
    func moveToLogin() {
        let vc = LoginRouter.createModule()
        vc.modalPresentationStyle = .fullScreen
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(vc, animated: true)
        } else {
            let naviVC = UINavigationController(rootViewController: vc)
            naviVC.modalPresentationStyle = .fullScreen
            viewController?.present(naviVC, animated: true)
        }
    }
}
