//
//  SuperSwitcherPresenter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import UIKit

class SuperSwitcherPresenter: SuperSwitcherPresenterProtocol {
    weak private var view: SuperSwitcherViewProtocol?
    private let router: SuperSwitcherWireframeProtocol?

    init(view: SuperSwitcherViewProtocol, router: SuperSwitcherWireframeProtocol?) {
        self.view = view
        self.router = router
    }

    func doCheckAuthorization() {
        if AppPreferences.instance.token == nil {
            router?.moveToLogin()
        } else {
            router?.moveToTodoList()
        }
    }
}
