//
//  TodoListPresenter.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import RxSwift
import RxRelay

class TodoListPresenter: TodoListPresenterProtocol {
    weak private var view: TodoListViewProtocol?
    var interactor: TodoListInteractorProtocol?
    private let router: TodoListWireframeProtocol

    init(view: TodoListViewProtocol, interactor: TodoListInteractorProtocol?, router: TodoListWireframeProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

}
