//
//  TodoListInteractor.swift
//  TodoList
//
//  Created Dung Nguyen on 3/6/20.
//  Copyright © 2020 Dung Nguyen. All rights reserved.
//
//  Template generated by Juanpe Catalán - @JuanpeCMiOS
//

import RxSwift

class TodoListInteractor: TodoListInteractorProtocol {
    weak var presenter: TodoListPresenterProtocol?
}
